---
# Resource Quota for Development Environment
apiVersion: v1
kind: ResourceQuota
metadata:
  name: composer-dev-quota
  namespace: composer-dev
  labels:
    environment: development
    app: airflow
    component: resource-management
    version: 2.x
    managed-by: terraform
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    requests.ephemeral-storage: "10Gi"
    limits.ephemeral-storage: "20Gi"
    pods: "10"
    services: "5"
    configmaps: "30"
    secrets: "30"
    persistentvolumeclaims: "5"
---
# Resource Quota for QA Environment
apiVersion: v1
kind: ResourceQuota
metadata:
  name: composer-qa-quota
  namespace: composer-qa
  labels:
    environment: qa
    app: airflow
    component: resource-management
    version: 2.x
    managed-by: terraform
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    requests.ephemeral-storage: "20Gi"
    limits.ephemeral-storage: "40Gi"
    pods: "20"
    services: "10"
    configmaps: "50"
    secrets: "50"
    persistentvolumeclaims: "10"
---
# Resource Quota for Production Environment
apiVersion: v1
kind: ResourceQuota
metadata:
  name: composer-prod-quota
  namespace: composer-prod
  labels:
    environment: production
    app: airflow
    component: resource-management
    version: 2.x
    managed-by: terraform
spec:
  hard:
    requests.cpu: "10"
    requests.memory: "24Gi"
    limits.cpu: "20"
    limits.memory: "48Gi"
    requests.ephemeral-storage: "50Gi"
    limits.ephemeral-storage: "100Gi"
    pods: "50"
    services: "15"
    configmaps: "100"
    secrets: "100"
    persistentvolumeclaims: "20"
---
# LimitRange for Development Environment
apiVersion: v1
kind: LimitRange
metadata:
  name: composer-dev-limits
  namespace: composer-dev
  labels:
    environment: development
    app: airflow
    component: resource-management
    version: 2.x
    managed-by: terraform
spec:
  limits:
    - type: Container
      default:
        cpu: "0.5"
        memory: "512Mi"
      defaultRequest:
        cpu: "0.1"
        memory: "128Mi"
      max:
        cpu: "2"
        memory: "2Gi"
      min:
        cpu: "50m"
        memory: "64Mi"
---
# LimitRange for QA Environment
apiVersion: v1
kind: LimitRange
metadata:
  name: composer-qa-limits
  namespace: composer-qa
  labels:
    environment: qa
    app: airflow
    component: resource-management
    version: 2.x
    managed-by: terraform
spec:
  limits:
    - type: Container
      default:
        cpu: "1"
        memory: "1Gi"
      defaultRequest:
        cpu: "0.2"
        memory: "256Mi"
      max:
        cpu: "4"
        memory: "4Gi"
      min:
        cpu: "100m"
        memory: "128Mi"
---
# LimitRange for Production Environment
apiVersion: v1
kind: LimitRange
metadata:
  name: composer-prod-limits
  namespace: composer-prod
  labels:
    environment: production
    app: airflow
    component: resource-management
    version: 2.x
    managed-by: terraform
spec:
  limits:
    - type: Container
      default:
        cpu: "1"
        memory: "2Gi"
      defaultRequest:
        cpu: "0.5"
        memory: "512Mi"
      max:
        cpu: "8"
        memory: "16Gi"
      min:
        cpu: "200m"
        memory: "256Mi"
---
# Special Resource Quota for Production Scheduler
apiVersion: v1
kind: ResourceQuota
metadata:
  name: composer-prod-scheduler-quota
  namespace: composer-prod
  labels:
    environment: production
    app: airflow
    component: scheduler
    version: 2.x
    managed-by: terraform
spec:
  hard:
    requests.cpu: "3"
    requests.memory: "8Gi"
    limits.cpu: "6"
    limits.memory: "16Gi"
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values: ["high-priority"]
---
# Special Resource Quota for Production Webserver
apiVersion: v1
kind: ResourceQuota
metadata:
  name: composer-prod-webserver-quota
  namespace: composer-prod
  labels:
    environment: production
    app: airflow
    component: webserver
    version: 2.x
    managed-by: terraform
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "8Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values: ["high-priority"]
---
# Special Resource Quota for Production Workers
apiVersion: v1
kind: ResourceQuota
metadata:
  name: composer-prod-worker-quota
  namespace: composer-prod
  labels:
    environment: production
    app: airflow
    component: worker
    version: 2.x
    managed-by: terraform
spec:
  hard:
    requests.cpu: "5"
    requests.memory: "16Gi"
    limits.cpu: "10"
    limits.memory: "24Gi"
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values: ["medium-priority"]